### PR TITLE
Add PowerNV platform

### PR DESCRIPTION
**Pull request by k0da**
This adds a PowerNV (Power Non Virtualized) bare metal platform.

Fixes boo#970582

Signed-off-by: Dinar Valeev <dvaleev@suse.com>

### CODE REVIEW

**Comment by aschnell** [comment]
The new flag is never used. Why do we need it then?

**Comment by k0da** [comment]
Mainly to be able to propose in yast-storage different layout. I see your point, maybe writing to xml is enough

**Comment by aschnell** [comment]
I see, so you basically just need the value in arch.info so that helper.rb in yast-storage can read it?

**Comment by k0da** [comment]
yes

**Comment by aschnell** [comment]
OK, LGTM.

**Pull request merged**
