### PR TITLE
export exceptions to ruby bindings (bnc#938561)

### PR DESCRIPTION
**Pull request by jreidinger**
tested manually, but have no clue how to test it automatic.

I test it manually with modified getEfiBoot that raising exception and ruby code:
```
require "storage"
env = Storage::Environment.new(true)
int = Storage::createStorageInterfacePid(env)
begin
  int.first.getEfiBoot
rescue Storage::SystemCmdException => e
  puts "exception #{e.message}"
ensure
  puts "after"
end
```

### CODE REVIEW

**Comment by aschnell** [comment]
The redesigned libstorage also passes exception to Ruby. I think a simpler implementation and esp. target language independent, https://github.com/aschnell/libstorage-bgl-eval/blob/master/bindings/storage.i. Testsuites also exist for Ruby, Python and Perl5.

**Comment by jreidinger** [comment]
@aschnell if I get it in pointed code you have to mark all methods that can raise exception, which looks quite hard to maintain, or do I overlook something?

**Comment by aschnell** [comment]
@jreidinger You are right that you have to maintain the list of exception for each function. Consider it part of the documentation. You could also use C++ throw-list declarations but those are marked deprecated in C++11 (see http://stackoverflow.com/questions/13841559/deprecated-throw-list-in-c11).

**Comment by aschnell** [comment]
Does the code work with exceptions that have additional functions?

**Comment by jreidinger** [comment]
@aschnell this solution needed to be modified only if new exception occur...from my POV we more often have method that throw exception then new exception.
We also discuss with HuHa additional functions of exceptions. Current PR do not support it, but it is easy to add it and I plan to do after this initial discussion about design and implementation.
So if you agree with this way I can add additional methods to exceptions, that can be used from ruby.

**Comment by aschnell** [comment]
@jreidinger Did you look at the generated code and its size? The code is inserted into every function wrapper. For me catching only those two exceptions increases the size of the ruby plugin from 2.1 to 2.7 MB. Imagine catching 20 exceptions: 8.1MB. So, for me the implementation is not OK.

**Comment by aschnell** [comment]
I discussed the use-case for exceptions for failures during probing with Stefan. They are not useful since you can only inform the user about a single problem, e.g. btrfs probing failed, but all probing that would have happened after the exception is also skipped. Callbacks are the way to go here - and they already exist.

**Comment by jreidinger** [comment]
@aschnell yes it have to be in every method call as it is implemented in swig this way, what can be improved is to move handling to own method, so it is not increased so much.... callbacks are fine for me, but we still need at least one top level exception handler, when exception occur to report it properly above and not cause sigabort as before, at least to get some information in logs.

**Comment by aschnell** [comment]
What do we need for what? The bug you mention was fixed one month ago.

**Comment by jreidinger** [comment]
@aschnell to easily catch and see exception for which callback missing or if some unexpected exception raised. That way you can it in better way in ruby, so it is easily to show it to customer and also to see it immediately from log. Maybe also some logging in generic catch can help.

**Comment by aschnell** [comment]
The purpose is not clear from the trello card.

**Comment by aschnell** [comment]
The implementation does not respect the exception class hierarchy.

**Comment by jreidinger** [comment]
I agree and can be easily fixed. What needs to be decided is which way to use?

**Comment by jreidinger** [comment]
updated with inheritance and attributes. Code I use for testing (require modified getEfiBoot to raise exception):

```
require "storage"
env = Storage::Environment.new(true)
int = Storage::createStorageInterfacePid(env)
begin
  int.first.getEfiBoot
rescue Storage::SystemCmdException => e
  puts "exception #{e.inspect}"
  puts "cmd caused by it #{e.cmd}"
  puts "retcode #{e.ret}"
  puts "stderr #{e.stderr.inspect}"
ensure
  puts "after"
end

```

**Comment by aschnell** [comment]
I don't understand why you persist in generating that code manually instead of giving the job to swig. The code now is 1. target-language dependent, 2. needs manually adaption when exceptions or their hierarchy change and 3. blows code and plugin size. Maintaining that code for a dozen of exceptions is terrible.

**Comment by jreidinger** [comment]
@aschnell even swig documentation suggest to catch exceptions using `%exception` block to handle also parts that are not catches by `%catch` directive. That is reason. Of course if you find it more suitable we can catch only general exception if it is not problem to get only msg and maybe backtrace.

**Comment by jreidinger** [comment]
quote from doc:
```
Since exception specifications are sometimes only used sparingly, this alone may not be enough to properly handle C++ exceptions. To do that, a different set of special SWIG directives are used. Consult the "Exception handling with %exception" section for details. The next section details a way of simulating an exception specification or replacing an existing one. 
```

**Comment by aschnell** [comment]
And the next section states: Exceptions are automatically handled for methods with an exception specification. Similar handling can be achieved for methods without exception specifications through the %catches feature.

**Comment by jreidinger** [comment]
@aschnell still question is if we want result that is produced if a catch missed. So if there is bug, if we want to get in ruby proper translated exception or if we want current behavior

**Comment by aschnell** [comment]
If you want that implement a ```catch(...)``` somewhere up in the stack, e.g. ruby-bindings or WFM.

**Comment by jreidinger** [comment]
@aschnell it is not called at all, it have to be translated on interface part. e.g. yast2-storage directly call libstorage-ruby, so ruby bindings neither WFM helps there.

**Comment by aschnell** [comment]
But the exception could be propagated through ruby to the code calling ruby. For an error message that would be enough.

**Comment by jreidinger** [comment]
OK, if we agreed that all exceptions going through swig interface and not through `%catches` is bug and we do not want to catch it in middle and only on top level, then trello task changed to mark all possible occurences that can raise these exceptions.

**Pull request closed without merging**
