### PR TITLE
Create partitions on GPT with empty name (bsc#1023818)

### PR DESCRIPTION
**Pull request by imobachgs**
Fixes [bsc#1023818](https://bugzilla.suse.com/show_bug.cgi?id=1023818) for `SLE 12 SP4`.

### CODE REVIEW

**Comment by aschnell** [comment]
LGTM

It the patched parted already available in SLE12 SP4?

**Comment by imobachgs** [comment]
@aschnell According to changes file, it was added one month ago:


```
Mon May  7 10:36:19 CEST 2018 - sparschauer@suse.de
[..]
  partition name in script mode (bsc#1023818, boo#1032562)
  - add: parted-mkpart-allow-empty-gpt-part-name.patch
```

**Comment by aschnell** [comment]
The change to Makefile.ci looks also good to me.

**Comment by aschnell** [comment]
LGTM

**Comment by imobachgs** [comment]
Thanks!

**Pull request merged**
